services:
  tododb:
    image: "docker.io/library/postgres:17.5"
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./container-data/postgresql:/var/lib/postgresql/data
    networks:
      - "todos"
networks:
  todos:
    driver: "bridge"
